// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWpn4TaDuNdLGYt5vgAxb2cpdmbkXa2GU',
    appId: '1:1074114930776:web:761ea32d9b04a40908022d',
    messagingSenderId: '1074114930776',
    projectId: 'givelife-8bea2',
    authDomain: 'givelife-8bea2.firebaseapp.com',
    storageBucket: 'givelife-8bea2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi4stKtFrsIvx3YzoxS-tVTRydiO3AtIk',
    appId: '1:1074114930776:android:ff2abdab90b3b6fc08022d',
    messagingSenderId: '1074114930776',
    projectId: 'givelife-8bea2',
    storageBucket: 'givelife-8bea2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWpn4TaDuNdLGYt5vgAxb2cpdmbkXa2GU',
    appId: '1:1074114930776:web:2d470dd9478f8eee08022d',
    messagingSenderId: '1074114930776',
    projectId: 'givelife-8bea2',
    authDomain: 'givelife-8bea2.firebaseapp.com',
    storageBucket: 'givelife-8bea2.firebasestorage.app',
  );
}
